### ISSUE TITLE
Python source code hard to read

### ISSUE THREAD

**Issue by PyvesB** [AObuchow/Eclipse-Spectrum-Theme#78] opened 2020-06-23 13:43 UTC
Hello again! 👋 

Python source code is very hard to read. See the following screenshot:
<img width="632" alt="Screenshot 2020-06-23 at 15 38 02" src="https://user-images.githubusercontent.com/10694593/85410627-9ee09a00-b567-11ea-99d6-d15e03ce03a4.png">

I'm guessing Pydev handles its own colour preferences. Obviously it's probably not manageable to handle every single third-party plugin, but in this case Pydev is the 5th most popular plugin on the markteplace, so may be worth adding support for it. 😉

**Comment by AObuchow** [comment] 2020-06-23 14:14
Agreed I think PyDev and other common Eclipse plugins should be supported ideally :) I've added some CSS preferences for Pydev quickly - I don't even have it installed so I haven't tested how it looks yet.

@PyvesB could you please update to the latest build and share a screenshot of how the Python colors look? Also feel free to submit tweaks to them if you want :)

**Comment by PyvesB** [comment] 2020-06-23 14:33
Hmm, this is what I get in a fresh workspace:
<img width="621" alt="Screenshot 2020-06-23 at 16 33 02" src="https://user-images.githubusercontent.com/10694593/85416841-3ac1d400-b56f-11ea-983d-e20bd5e3a428.png">

**Comment by AObuchow** [comment] 2020-06-23 14:47
Thanks for the screenshot. 
I referenced https://github.com/fabioz/Pydev/blob/cf765a4925da47f24043a8ac67cf186c7bce6cc6/plugins/org.python.pydev/css/dark/e4-pydev-dark_preferencestyle.css in the latest patch.

However, the blue color used for methods still seems unreadable. Please update and provide another screenshot to see how it looks now (I apologize I have yet to simply download PyDev..)

**Comment by PyvesB** [comment] 2020-06-23 15:23
I'm under the impression that my installation is not updating properly. I pulled in the latest version of the plugin, but I don't seem to see any changes from this issue, #76 or #79. I've tried disabling Oomph and using a fresh workspace, to no avail. Unlike #63, I'm not able to find these properties in the `.metadata` folder.

**Comment by AObuchow** [comment] 2020-06-23 15:27
No worries, I’ll try bumping the version to 1.0.8 and see if that helps :)

**Comment by PyvesB** [comment] 2020-06-23 15:28
Digging further, there _does_ seem to be a problem.

Installation Details -> Installed Software shows  `Modern Dark Theme 1.0.7.202006231446	com.aobuchow.themes.moderndark.feature.feature.group	aobuchow`

But Installation Details -> Plug-ins shows `aobuchow	Modern Dark Theme	1.0.7.202006221505	com.aobuchow.themes.moderndark`

**Comment by AObuchow** [comment] 2020-06-23 15:31
Ahh thank you for spotting that !!

I’m not sure if the issue is in the build or the CI or elsewhere. If you have the time, you could try cloning the repo’s master branch and do `mvn verify` and install from the local updatesite.

We can then determine if local builds are fine or if there’s an issue with them currently.

**Comment by PyvesB** [comment] 2020-06-23 15:37
My gut feeling is that there's nothing wrong with this plugin. This same thing happened to me once in the past with WildWebDeveloper. I did revert my installation a couple of times between yesterday and this morning, I'm wondering whether this got things messed up. I'll try cleaning up my p2 caches and see if that helps before investigating whether there's anything wrong with this project.

**Comment by AObuchow** [comment] 2020-06-23 15:50
No worries, let me know if you're able to resolve the issue!

**Comment by PyvesB** [comment] 2020-06-24 07:36
For the record, I had to modify these two files in my Eclipse installation:
Eclipse/configuration/org.eclipse.update/platform.xml
Eclipse/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info

They had ended up containing duplicate entries of Modern Dark theme with outdated version numbers.

**Comment by PyvesB** [comment] 2020-06-24 07:39
Python source code is now fully readable!
<img width="480" alt="Screenshot 2020-06-24 at 09 39 08" src="https://user-images.githubusercontent.com/10694593/85516528-94bdaa80-b5fe-11ea-8ee8-567fce418b30.png">

**Comment by AObuchow** [comment] 2020-06-24 11:57
@PyvesB thanks for the info, could be useful in the future.

Glad the python syntax coloring looks better now :) I'm going to close this issue for the time being.

**Closed by AObuchow** 2020-06-24 11:57 UTC
Labels: bug
